github: andrea-mariadb-2, andipandi111, andrea-mariadb
patreon: andrea_mariadb
ko_fi: 
open_collective: andrea-mariadb
tidelift: andrea_mariadb.npm
community_bridge: andrea_mariadb
liberapay: andrea-mariadb
issuehunt: andrea-mariadb
otechie: andrea_mariadb
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: 'https://www.youtube.com/@littleninja76133', 'https://www.youtube.com/channel/UCeTsecOxtD8zuDKPpcL9crg'
